runtime: nodejs
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
  - url: /
    static_dir: frontend/build
